/**
 * Gate init — interactive project setup
 * Detects stack, installs pre-commit hook, creates .gateignore, updates .gitignore
 */

const fs = require('fs');
const path = require('path');
const { detectStack, getDefaultIgnorePatterns } = require('./config');
const { install } = require('./installer');

const ENV_PATTERNS = ['.env', '.env.local', '.env.*.local', '.gate/'];
const ENV_SECTION_HEADER = '# Gate — prevent committing secrets';

/**
 * Check whether a directory is a git repository root (has a .git entry)
 *
 * @param {string} dir
 * @returns {boolean}
 */
function isGitRepo(dir) {
  return fs.existsSync(path.join(dir, '.git'));
}

/**
 * Build the .gateignore file content for the given stacks
 *
 * @param {string[]} stacks
 * @returns {string}
 */
function buildGateignoreContent(stacks) {
  const stackLabel = stacks.length > 0 ? stacks.join(', ') : 'general';
  const patterns = getDefaultIgnorePatterns(stacks);
  const lines = [
    '# .gateignore — Gate scanner ignore patterns',
    '# Generated by gate init',
    '',
    `# Default patterns for ${stackLabel}`,
    ...patterns,
    '',
  ];
  return lines.join('\n');
}

/**
 * Determine which env patterns are missing from the existing .gitignore content
 *
 * @param {string} existing  Existing .gitignore text (may be empty)
 * @returns {string[]}       Patterns not yet present
 */
function missingEnvPatterns(existing) {
  const lines = existing.split('\n').map(l => l.trim());
  return ENV_PATTERNS.filter(p => !lines.includes(p));
}

/**
 * Run gate init in the given directory
 *
 * @param {string} [dir]  Directory to initialise (defaults to cwd)
 * @returns {Promise<{ hookInstalled: boolean, gateignoreCreated: boolean, gitignoreUpdated: boolean, stacks: string[] }>}
 */
async function runInit(dir) {
  dir = dir || process.cwd();

  // 1. Verify we are inside a git repository
  if (!isGitRepo(dir)) {
    throw new Error(
      'Not a git repository. Run `git init` first, then run `gate init` again.'
    );
  }

  // 2. Detect the project stack
  const stacks = detectStack(dir);

  // 3. Install the pre-commit hook (best-effort — may already exist)
  let hookInstalled = false;
  try {
    install('pre-commit', dir);
    try { install('pre-push', dir); } catch {}
    hookInstalled = true;
  } catch {
    hookInstalled = false;
  }

  // 4. Create .gateignore (only if it doesn't already exist)
  const gateignorePath = path.join(dir, '.gateignore');
  let gateignoreCreated = false;
  if (!fs.existsSync(gateignorePath)) {
    fs.writeFileSync(gateignorePath, buildGateignoreContent(stacks), 'utf8');
    gateignoreCreated = true;
  }

  // 5. Update .gitignore — add env patterns if missing
  const gitignorePath = path.join(dir, '.gitignore');
  const existingGitignore = fs.existsSync(gitignorePath)
    ? fs.readFileSync(gitignorePath, 'utf8')
    : '';

  const missing = missingEnvPatterns(existingGitignore);
  let gitignoreUpdated = false;
  if (missing.length > 0) {
    const addition = [
      '',
      ENV_SECTION_HEADER,
      ...missing,
      '',
    ].join('\n');
    fs.writeFileSync(gitignorePath, existingGitignore + addition, 'utf8');
    gitignoreUpdated = true;
  }

  return { hookInstalled, gateignoreCreated, gitignoreUpdated, stacks };
}

module.exports = { runInit };
