/**
 * Interactive Remediation TUI
 *
 * Presents findings one at a time with single-keypress actions.
 * Uses Node's readline raw mode — no external dependencies.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const { formatFinding } = require('./output');
const { assessExposure, formatExposure } = require('./exposure');
const fixer = require('./fixer');
const vault = require('./vault');
const { getRemediation, getActionLabel } = require('./remediation');
const { startIncidentResponse } = require('./incident');

// ─── ANSI helpers ───────────────────────────────────────────────────────────

const BOLD  = '\x1b[1m';
const DIM   = '\x1b[2m';
const RESET = '\x1b[0m';
const CYAN  = '\x1b[36m';
const GREEN = '\x1b[32m';
const RED   = '\x1b[31m';
const YELLOW = '\x1b[33m';

function c(useColor, code, text) {
  return useColor ? `${code}${text}${RESET}` : text;
}

// ─── Low-level keypress handler ─────────────────────────────────────────────

/**
 * Wait for a single keypress from a fixed set of valid keys.
 *
 * @param {string[]} validKeys  — lowercase single characters
 * @param {Function} render     — called once to display the prompt
 * @param {object}   [options]
 * @returns {Promise<string|null>}  — the pressed key, or null for non-TTY
 */
function promptChoice(validKeys, render, options = {}) {
  return new Promise((resolve) => {
    if (!process.stdin.isTTY) {
      resolve(null);
      return;
    }

    render();

    process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.setEncoding('utf8');

    const handler = (key) => {
      // Ctrl+C → abort.
      if (key === '\u0003') {
        process.stdin.setRawMode(false);
        process.stdin.removeListener('data', handler);
        process.exit(1);
      }

      const lower = key.toLowerCase();
      if (validKeys.includes(lower)) {
        process.stdin.setRawMode(false);
        process.stdin.pause();
        process.stdin.removeListener('data', handler);
        resolve(lower);
      }
      // Ignore invalid keys silently.
    };

    process.stdin.on('data', handler);
  });
}

// ─── Hook action menu ────────────────────────────────────────────────────────

/**
 * Display the pre-commit hook menu and return the chosen action.
 *
 * @param {boolean} useColor
 * @returns {Promise<'f'|'i'|'a'>}
 */
async function promptHookAction(useColor) {
  const choice = await promptChoice(
    ['f', 'i', 'a'],
    () => {
      process.stdout.write('\n');
      process.stdout.write(
        `  ${c(useColor, BOLD, '[f]')} Fix all    ` +
        `${c(useColor, BOLD, '[i]')} Interactive    ` +
        `${c(useColor, BOLD, '[a]')} Abort\n`
      );
      process.stdout.write('  > ');
    }
  );
  process.stdout.write('\n');
  return choice;
}

// ─── .gateignore helper ──────────────────────────────────────────────────────

/**
 * Append a rule+file entry to .gateignore.
 *
 * @param {string} ruleId
 * @param {string} filePath  — absolute path to the file containing the secret
 * @param {string} repoDir   — repo root (used to derive relative path)
 */
function addToGateIgnore(ruleId, filePath, repoDir) {
  const ignorePath = path.join(repoDir, '.gateignore');
  const relPath = path.relative(repoDir, filePath);
  const entry = `[rule:${ruleId}] ${relPath}\n`;

  let existing = '';
  if (fs.existsSync(ignorePath)) {
    existing = fs.readFileSync(ignorePath, 'utf8');
  } else {
    existing = '# Gate ignore rules — generated by gate scan --interactive\n';
  }

  if (!existing.endsWith('\n')) existing += '\n';
  fs.writeFileSync(ignorePath, existing + entry);
}

// ─── Finding walkthrough ─────────────────────────────────────────────────────

/**
 * Walk through findings one at a time, prompting for action on each.
 *
 * @param {object[]} findings
 * @param {object}   options
 * @param {boolean}  [options.color]
 * @param {string}   [options.repoDir]
 * @param {number}   [options.context_lines]
 * @returns {Promise<{summary: object, modifiedFiles: string[]}>}
 */
async function runInteractive(findings, options = {}) {
  const useColor = options.color === true;
  const repoDir  = options.repoDir || process.cwd();

  const summary = { fixed: 0, ignored: 0, vaulted: 0, skipped: 0, responded: 0 };
  const modifiedFiles = [];
  const actions = new Map(); // track which findings have been acted on

  let i = 0;
  while (i < findings.length) {
    const finding = findings[i];

    // ── Header ─────────────────────────────────────────────────────────────
    console.log('');
    console.log(
      c(useColor, DIM, '─'.repeat(60))
    );
    console.log(
      `  ${c(useColor, BOLD, `Finding ${i + 1} of ${findings.length}`)}` +
      `  ${c(useColor, DIM, finding.ruleName || finding.ruleId)}`
    );
    console.log('');

    // ── Code context ───────────────────────────────────────────────────────
    let fileLines = [];
    try {
      if (finding.file && fs.existsSync(finding.file)) {
        fileLines = fs.readFileSync(finding.file, 'utf8').split('\n');
      }
    } catch { /* ignore read errors */ }

    const formatted = formatFinding(finding, fileLines, {
      color: useColor,
      context_lines: options.context_lines || 2,
    });
    console.log(formatted);

    // ── Exposure assessment ─────────────────────────────────────────────────
    const exposure = await assessExposure(finding.file, repoDir);
    const exposureLabel = formatExposure(exposure, useColor);
    console.log('');
    console.log(`  Exposure: ${exposureLabel}`);
    if (exposure.details) {
      console.log(`  ${c(useColor, DIM, exposure.details)}`);
    }

    // ── Options ────────────────────────────────────────────────────────────
    const isPushed = exposure.level === 'PUSHED';
    let action;

    if (isPushed) {
      // PUSHED — respond, fix, skip, previous, jump, explain.
      action = await promptChoice(
        ['r', 'f', 's', 'p', 'j', '?'],
        () => {
          process.stdout.write('\n');
          process.stdout.write(
            `  ${c(useColor, BOLD, '[r]')} Respond   ` +
            `${c(useColor, DIM, 'Start incident response (recommended)')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[f]')} Fix code  ` +
            `${c(useColor, DIM, 'Extract from source (NOT sufficient alone)')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[s]')} Skip\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[p]')} Previous  ` +
            `${c(useColor, DIM, 'Go to previous finding')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[j]')} Jump      ` +
            `${c(useColor, DIM, 'Jump to finding #')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[?]')} Explain   ` +
            `${c(useColor, DIM, 'Full remediation guide + compliance')}\n`
          );
          process.stdout.write('  > ');
        }
      );
    } else {
      // LOCAL / COMMITTED / UNKNOWN — full option set.
      action = await promptChoice(
        ['f', 'v', 'i', 's', 'p', 'j', '?'],
        () => {
          process.stdout.write('\n');
          process.stdout.write(
            `  ${c(useColor, BOLD, '[f]')} Fix       ` +
            `${c(useColor, DIM, 'Extract to .env, update code')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[v]')} Vault     ` +
            `${c(useColor, DIM, 'Encrypt with gate vault')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[i]')} Ignore    ` +
            `${c(useColor, DIM, 'Add to .gateignore')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[s]')} Skip      ` +
            `${c(useColor, DIM, 'Skip for now')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[p]')} Previous  ` +
            `${c(useColor, DIM, 'Go to previous finding')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[j]')} Jump      ` +
            `${c(useColor, DIM, 'Jump to finding #')}\n`
          );
          process.stdout.write(
            `  ${c(useColor, BOLD, '[?]')} Explain   ` +
            `${c(useColor, DIM, 'Full remediation guide + compliance')}\n`
          );
          process.stdout.write('  > ');
        }
      );
    }

    process.stdout.write('\n');

    // ── Execute action ──────────────────────────────────────────────────────
    if (action === 'p') {
      if (i > 0) i--;
      continue;

    } else if (action === 'j') {
      process.stdout.write(`  Jump to [1-${findings.length}]: `);
      const rl = require('readline').createInterface({ input: process.stdin, output: process.stdout });
      const target = await new Promise(resolve => rl.on('line', line => { rl.close(); resolve(line.trim()); }));
      const num = parseInt(target, 10);
      if (num >= 1 && num <= findings.length) {
        i = num - 1;
      }
      continue;

    } else if (action === 'f') {
      const result = fixer.fixFinding(finding, finding.file, { repoDir });
      if (result && result.fixed) {
        summary.fixed++;
        modifiedFiles.push(finding.file);
        // Write to .env and ensure .gitignore coverage
        if (result.envEntry) {
          const envPath = path.join(repoDir, '.env');
          fixer.updateEnvFile(envPath, result.envEntry.varName, result.envEntry.value);
          fixer.ensureGitignore(repoDir);
        }
        console.log(
          `  ${c(useColor, GREEN, '✓')} Fixed — secret extracted to .env` +
          (result.envEntry ? ` as ${result.envEntry.varName}` : '')
        );
        if (result.note) {
          console.log(`  ${c(useColor, DIM, result.note)}`);
        }
      } else {
        console.log(`  ${c(useColor, YELLOW, '!')} Could not auto-fix — please fix manually`);
      }
      actions.set(i, action);

    } else if (action === 'v') {
      try {
        const encrypted = vault.encrypt(finding.match || '');
        const content = fs.readFileSync(finding.file, 'utf8');
        const vaultRef = `VAULT:${encrypted.slice(0, 20)}`;
        const updated = content.split(finding.match).join(vaultRef);
        if (updated !== content) {
          fs.writeFileSync(finding.file, updated);
          modifiedFiles.push(finding.file);
          summary.vaulted++;
          console.log(`  ${c(useColor, GREEN, '✓')} Secret replaced with vault reference`);
        } else {
          summary.vaulted++;
          console.log(`  ${c(useColor, GREEN, '✓')} Encrypted (secret not found in source for inline replacement)`);
          console.log(`  ${c(useColor, DIM, encrypted.slice(0, 40) + '...')}`);
        }
      } catch (err) {
        console.log(`  ${c(useColor, YELLOW, '!')} Vault error: ${err.message}`);
      }
      actions.set(i, action);

    } else if (action === 'i') {
      addToGateIgnore(finding.ruleId, finding.file, repoDir);
      summary.ignored++;
      console.log(`  ${c(useColor, GREEN, '✓')} Added to .gateignore`);
      actions.set(i, action);

    } else if (action === 'r') {
      await startIncidentResponse(finding, { cwd: options.repoDir || process.cwd() });
      summary.responded++;
      actions.set(i, action);

    } else if (action === '?') {
      // Show remediation guide.
      const remediation = getRemediation(finding.ruleId);
      const actionLabel = getActionLabel(remediation.action);

      console.log('');
      console.log(`  ${c(useColor, BOLD, 'Remediation Guide')} — ${c(useColor, CYAN, actionLabel)}`);
      console.log('');
      console.log(`  ${remediation.guide}`);
      if (remediation.link) {
        console.log('');
        console.log(`  ${c(useColor, DIM, remediation.link)}`);
      }
      console.log('');

      // After showing explanation, prompt again (same finding).
      continue;

    } else if (action === 's' || action === null) {
      summary.skipped++;
      console.log(`  ${c(useColor, DIM, 'Skipped')}`);
      actions.set(i, 's');
    }

    i++;
  }

  // ── Batch action for skipped findings ──────────────────────────────────────
  const skippedCount = findings.length - actions.size;
  if (skippedCount > 0 && summary.skipped > 0 && process.stdin.isTTY) {
    const batchAction = await promptChoice(
      ['i', 'l', 'q'],
      () => {
        process.stdout.write(`\n  ${skippedCount} finding(s) were skipped.\n`);
        process.stdout.write(
          `  ${c(useColor, BOLD, '[i]')} Ignore all skipped  ` +
          `${c(useColor, BOLD, '[l]')} Leave as-is  ` +
          `${c(useColor, BOLD, '[q]')} Quit\n`
        );
        process.stdout.write('  > ');
      }
    );
    process.stdout.write('\n');
    if (batchAction === 'i') {
      let batchIgnored = 0;
      for (let idx = 0; idx < findings.length; idx++) {
        if (!actions.has(idx)) {
          addToGateIgnore(findings[idx].ruleId, findings[idx].file, repoDir);
          batchIgnored++;
        }
      }
      summary.ignored += batchIgnored;
      summary.skipped -= batchIgnored;
      console.log(`  ${c(useColor, GREEN, '\u2713')} Added ${batchIgnored} entries to .gateignore`);
    }
  }

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log('');
  console.log(c(useColor, DIM, '─'.repeat(60)));
  console.log(`  ${c(useColor, BOLD, 'Interactive session complete')}`);
  console.log('');

  const parts = [];
  if (summary.fixed > 0)     parts.push(`${summary.fixed} fixed`);
  if (summary.vaulted > 0)   parts.push(`${summary.vaulted} vaulted`);
  if (summary.ignored > 0)   parts.push(`${summary.ignored} ignored`);
  if (summary.responded > 0) parts.push(`${summary.responded} responded`);
  if (summary.skipped > 0)   parts.push(`${summary.skipped} skipped`);

  if (parts.length > 0) {
    console.log(`  ${parts.join(' · ')}`);
  } else {
    console.log(`  No actions taken`);
  }
  console.log('');

  return { summary, modifiedFiles };
}

// ─── Exports ─────────────────────────────────────────────────────────────────

module.exports = {
  promptHookAction,
  runInteractive,
  promptChoice,
};
