#!/usr/bin/env node
'use strict';

/**
 * Documentation generator for Gate's rule counts.
 *
 * Computes the live rule statistics from src/cli/rules.js (post-loader, so the
 * FORTRESS pack is included) and rewrites the content between
 *   <!-- GATE:RULES:BEGIN -->  and  <!-- GATE:RULES:END -->
 * markers in README.md and GUIDE.md.
 *
 * Usage:
 *   node scripts/gen-docs.js           # rewrite the docs in place
 *   node scripts/gen-docs.js --check   # exit 1 if the docs are out of date
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const { RULES, getRules } = require(path.join(ROOT, 'src', 'cli', 'rules.js'));

const BEGIN = '<!-- GATE:RULES:BEGIN -->';
const END = '<!-- GATE:RULES:END -->';

const TARGETS = [
  path.join(ROOT, 'README.md'),
  path.join(ROOT, 'GUIDE.md'),
];

function loadRawFortressCount() {
  try {
    const data = require(path.join(ROOT, 'rules', 'rules.json'));
    return Array.isArray(data.rules) ? data.rules.length : 0;
  } catch {
    return 0;
  }
}

function computeStats() {
  const all = getRules();
  const builtin = RULES.length;
  const total = all.length;
  const fortressUnique = total - builtin;
  const fortressRaw = loadRawFortressCount();

  const bySeverity = {};
  const byCategory = {};
  for (const rule of all) {
    const sev = rule.severity || 'unknown';
    bySeverity[sev] = (bySeverity[sev] || 0) + 1;
    const cat = rule.category || 'Uncategorized';
    byCategory[cat] = (byCategory[cat] || 0) + 1;
  }

  return {
    total,
    builtin,
    fortressUnique,
    fortressRaw,
    bySeverity,
    byCategory,
    ids: all.map((r) => r.id).sort(),
  };
}

const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low'];

function renderBlock(stats) {
  const sevParts = SEVERITY_ORDER
    .filter((s) => stats.bySeverity[s])
    .map((s) => `${s} ${stats.bySeverity[s]}`);
  // Any severities outside the canonical order (shouldn't happen) appended.
  for (const s of Object.keys(stats.bySeverity)) {
    if (!SEVERITY_ORDER.includes(s)) sevParts.push(`${s} ${stats.bySeverity[s]}`);
  }

  const categoryRows = Object.entries(stats.byCategory)
    .sort((a, b) => (b[1] - a[1]) || a[0].localeCompare(b[0]))
    .map(([cat, n]) => `| ${cat} | ${n} |`)
    .join('\n');

  return [
    '<!-- Generated by scripts/gen-docs.js — do not edit by hand. Run `npm run docs`. -->',
    `**${stats.total} unique detection rules** (${stats.builtin} built-in + ${stats.fortressRaw} FORTRESS pack, deduplicated).`,
    '',
    `By severity: ${sevParts.join(' · ')}`,
    '',
    '| Category | Rules |',
    '|----------|:-----:|',
    categoryRows,
  ].join('\n');
}

function applyToFile(filePath, block, check) {
  const original = fs.readFileSync(filePath, 'utf8');
  const re = new RegExp(`${BEGIN}[\\s\\S]*?${END}`);
  if (!re.test(original)) {
    throw new Error(
      `${path.basename(filePath)} is missing the ${BEGIN} / ${END} markers — insert them where the rule counts live.`
    );
  }
  const replacement = `${BEGIN}\n${block}\n${END}`;
  const updated = original.replace(re, replacement);

  if (check) {
    return updated === original;
  }
  if (updated !== original) {
    fs.writeFileSync(filePath, updated);
  }
  return true;
}

function main() {
  const check = process.argv.includes('--check');
  const stats = computeStats();
  const block = renderBlock(stats);

  let drift = false;
  for (const file of TARGETS) {
    let inSync;
    try {
      inSync = applyToFile(file, block, check);
    } catch (err) {
      console.error(`gen-docs: ${err.message}`);
      process.exit(1);
    }
    if (check && !inSync) {
      drift = true;
      console.error(`gen-docs: ${path.basename(file)} rule docs are out of date — run \`npm run docs\`.`);
    } else if (!check) {
      console.log(`gen-docs: updated ${path.basename(file)}`);
    }
  }

  if (check) {
    if (drift) process.exit(1);
    console.log(`gen-docs: docs in sync (${stats.total} rules).`);
  } else {
    console.log(`gen-docs: ${stats.total} rules (${stats.builtin} built-in + ${stats.fortressUnique} unique FORTRESS).`);
  }
}

main();
